name: diameter_rs
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0-293.0.dev

# Add regular dependencies here.
dependencies:
  xml: ^6.6.1
  # path: ^1.8.0

dev_dependencies:
  benchmark_harness: ^2.3.1
  lints: ^5.0.0
  test: ^1.24.0
